version: "3"
services:
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./dist:/dist
    command: npm run start-dev
    depends_on:
      - elasticsearch
    links: 
      - elasticsearch
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200